## Import the neccessary libraries and files

In [1]:
import numpy as np
import pandas as pd
import shelve
import keras_experiment
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

## Import shelve file for three concetrations: 

**15000 ppb, 1500 ppb, 150 ppb**

In [2]:
filename='shelve_save_data.out'

my_shelf = shelve.open(filename)
for key in my_shelf:
    globals()[key]=my_shelf[key]
my_shelf.close()

### Preprocess the data

In [3]:
whole_data = np.zeros((20000, 1600))
print(whole_data.shape)
whole_data[0:2500] = np.copy(data_15000[0])
whole_data[2500:5000] = np.copy(data_15000[1])
whole_data[5000:7500] = np.copy(data_15000[2])
whole_data[7500:10000] = np.copy(data_15000[3])
whole_data[10000:12500] = np.copy(data_1500[0])
whole_data[12500:15000] = np.copy(data_1500[1])
whole_data[15000:17500] = np.copy(data_1500[2])
whole_data[17500:20000] = np.copy(data_1500[3])

training_data = np.empty_like(whole_data)
print(training_data)


max_of_each_row = whole_data.max(axis=1)
print(max_of_each_row)
training_data = np.copy(whole_data / max_of_each_row[:, np.newaxis])
    
print(training_data)
    
labels = np.zeros((20000, 2))
labels[0:10000,0] = 1
labels[10000:20000,1] = 1

idx = np.random.permutation(len(labels))
# plt.plot(f_sup, training_data[], '-')#, label='one spectrum')
# plt.legend()
# plt.show()
X = np.copy(training_data)[idx]
y = np.copy(labels)[idx]
x_train, y_train = X[:16000], y[:16000]
x_test, y_test = X[16000:], y[16000:]
x_train_another, y_train_another = np.copy(X), np.copy(y)


(20000, 1600)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[286.2 361.8 324.  ... 362.2 405.8   0. ]


/home/akula/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


[[0.17540182 0.17679944 0.17051013 ... 0.89378057 0.90775681 0.90915444]
 [0.14814815 0.12327253 0.13377557 ... 0.74626866 0.74074074 0.79049198]
 [0.22345679 0.19814815 0.21049383 ... 0.98580247 0.98518519 0.94691358]
 ...
 [0.140254   0.13528437 0.14522363 ... 0.95637769 1.         0.99282165]
 [0.19418433 0.15426318 0.16855594 ... 0.98570724 0.99112863 0.97092164]
 [       nan        nan        nan ...        nan        nan        nan]]


In [4]:
array_sum = training_data.sum(axis=1)
print(array_sum.shape)
array_has_nan = np.where(np.isnan(array_sum) == True)

(20000,)


In [5]:
print(array_has_nan)

(array([ 2499,  2549,  2599,  2649,  2699,  2749,  2799,  2849,  2899,
        2949,  2999,  3049,  3099,  3149,  3199,  3249,  3299,  3349,
        3399,  3449,  3499,  3549,  3599,  3649,  3699,  3749,  3799,
        3849,  3899,  3949,  3999,  4049,  4099,  4149,  4199,  4249,
        4299,  4349,  4399,  4449,  4499,  4549,  4599,  4649,  4699,
        4749,  4799,  4849,  4899,  4949,  4999,  7499,  9999, 12499,
       14999, 17499, 19999]),)


In [6]:
indeces_nan = np.unique(array_has_nan[0])
print(indeces_nan)

[ 2499  2549  2599  2649  2699  2749  2799  2849  2899  2949  2999  3049
  3099  3149  3199  3249  3299  3349  3399  3449  3499  3549  3599  3649
  3699  3749  3799  3849  3899  3949  3999  4049  4099  4149  4199  4249
  4299  4349  4399  4449  4499  4549  4599  4649  4699  4749  4799  4849
  4899  4949  4999  7499  9999 12499 14999 17499 19999]


### Define model

In [ ]:
model = keras.Sequential(
    [
        keras.Input(shape=(1600,)),
        layers.Dense(400, activation="relu"),
        layers.Dense(100, activation="relu"),
        layers.Dense(2, activation="softmax"),
    ]
)

### Compile model

In [ ]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=['accuracy'],
)

In [ ]:
history = model.fit(x_train_another, y_train_another, validation_split=0.2, epochs=30, batch_size=256, verbose=2)

In [ ]:
np.mean(model.predict(x_test).argmax(axis=-1) == y_test.argmax(axis=-1))

In [ ]:
# list all data in history
print(history.history.keys())

In [ ]:
# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()