# Reading data
## This notebook is to provide all the data again if the archives of the data are somehow lost

### Import necessary modules

In [1]:
from tools.ramanflow.read_data import ReadData as RD
import numpy as np

### 2021-03-19 data

In [2]:
f_sup_0319, MG_colloidal_SERS_test_20210319 = RD.read_dir_tiff_files('data/20210319 MG colloidal SERS test')

### 2021-03-31 data

In [3]:
f_sup_0331, MG_colloidal_SERS_test_20210331 = RD.read_dir_tiff_files('data/20210331 MG colloidal SERS2')
_, batch2_power_test_20210331 = RD.read_dir_tiff_files('data/20210331 MG colloidal SERS2/batch2_power_test')
_, HWP36_to_80_step2_10s_20210331 = RD.read_dir_tiff_files('data/20210331 MG colloidal SERS2/batch2_power_test/10s_from_HWP36_to_80_step2')

### 2021-04-27 data

In [4]:
f_sup_0427, MG_ACE_ACETAMIPRID_colloidal_SERS3_20210427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3')
_, MG_1_5ppb_0427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/1_5ppb_MG')
_, MG_15ppb_0427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/15ppb_MG')
_, MG_150ppb_0427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/150ppb_MG')
_, ACE_0427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/ACE')
_, Acetamiprid_0427 = RD.read_dir_tiff_files('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/Acetamiprid')

### 2021-07-07 data

In [5]:
f_sup_0707, Carbendazim_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/1_Carbendanzim')
_, Carbendazim_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/1_Carbendanzim/HWP42 to 82 step4 1s 5x5map 10xzoom')
_, Thiacloprid_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/2_Thiacloprid')
_, Thiacloprid_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/2_Thiacloprid/HWP42 to 82 step4 1s 5x5map 10xzoom')
_, Imidacloprid_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/3_Imidacloprid')
_, Imidacloprid_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/3_Imidacloprid/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Acetamiprid_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/4_Acetamiprid')
_, Acetamiprid_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/4_Acetamiprid/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Acephate_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/5_Acephate')
_, Acephate_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/5_Acephate/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, MG_150ppb_0707 = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/150ppb_MG test')
_, MG_150ppb_0707_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/150ppb_MG test/HWP42 to 82 step4 1s 5x5map 10xzoom new colloids')
_, Acetamiprid_with_150ppb_MG = RD.read_tiff_file('data/20210707 colloidal SERS multiple analytes/Mix Acetamiprid with 0.1ml of 150ppb_MG/2ml Acetamiprid colloidal plus 0.1ml 150ppb_MG mix 1s 32x32 HWP50.tif')
_, Acetamiprid_with_150ppb_MG_power_test = RD.read_dir_tiff_files('data/20210707 colloidal SERS multiple analytes/Mix Acetamiprid with 0.1ml of 150ppb_MG/HWP42 to 62 step2 1s 6x6map 10xzoom')

### 2021-07-22 data

In [6]:
f_sup_0722, colloidal_SERS_multiple_analytes_20210722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes')
_, Carbendazim_0722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/1_Carbendanzim')
_, Carbendazim_0722_power_test = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/1_Carbendanzim/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Thiacloprid_0722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/2_Thiacloprid')
_, Thiacloprid_0722_power_test = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/2_Thiacloprid/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Imidacloprid_0722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/3_Imidacloprid')
_, Imidacloprid_0722_power_test = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/3_Imidacloprid/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Acetamiprid_0722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/4_Acetamiprid')
_, Acetamiprid_0722_power_test = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/4_Acetamiprid/HWP42 to 62 step2 1s 6x6map 10xzoom')
_, Acephate_0722 = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/5_Acephate')
_, Acephate_0722_power_test = RD.read_dir_tiff_files('data/20210722 colloidal SERS multiple analytes/5_Acephate/HWP42 to 62 step2 1s 6x6map 10xzoom')

### 2021-08-10 data

In [7]:
f_sup_0810, Carbendazim_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/1')
_, Carbendazim_Acetamiprid_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/1+4')
_, Carbendazim_Acetamiprid_Acephate_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/1+4+5')
_, Carbendazim_Acephate_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/1+5')
_, Acetamiprid_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/4')
_, Acetamiprid_Acephate_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/4+5')
_, Acephate_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/5')
_, colloids_0810 = RD.read_dir_tiff_files('data/20210810 SERS timed immersion experiment/colloidal solution')

### 2021-08-11 data

In [8]:
f_sup_0811, Carbendazim_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/1')
_, Carbendazim_Acetamiprid_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/1+4')
_, Carbendazim_Acetamiprid_Acephate_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/1+4+5')
_, Carbendazim_Acephate_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/1+5')
_, Acetamiprid_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/4')
_, Acetamiprid_Acephate_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/4+5')
_, Acephate_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/5')
_, MG_150ppb_0811 = RD.read_dir_tiff_files('data/20210811 SERS timed immersion experiment/MG_150ppb')

### 2021-08-13 data

In [9]:
f_sup_0813, Carbendazim_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1')
_, Carbendazim_Acetamiprid_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1+4')
_, Carbendazim_Acetamiprid_Acephate_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1+4+5')
_, Carbendazim_Acephate_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1+5')
_, Old_Carbendazim_old_colloids_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1o+o')
_, Carbendazim_old_colloids_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/1+o')
_, Acetamiprid_Acephate_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/4+5')
_, Acetamiprid_old_colloids_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/4+o')
_, Old_Acetamiprid_old_colloids_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/4o+o')
_, Acetamiprid_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/4')
_, Acephate_0813 = RD.read_dir_tiff_files('data/20210813 SERS timed immersion experiment/5')

### 2021-03-18 data

In [10]:
f_sup_0818, Carbendazim_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1')
_, Carbendazim_Acetamiprid_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1+4')
_, Carbendazim_Acetamiprid_Acephate_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1+4+5')
_, Carbendazim_Acephate_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1+5')
_, Carbendazim_old_colloids_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1+o')
_, Carbendazim_old_colloids_v2_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1o+Co')
_, Carbendazim_old_colloids_v3_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/1oo+oo')
_, Acetamiprid_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/4')
_, Acetamiprid_Acephate_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/4+5')
_, Acetamiprid_old_colloids_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/4+o')
_, Acetamiprid_old_colloids_v2_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/4o+o')
_, Acetamiprid_old_colloids_v3_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/4oo+oo')
_, Acephate_0818 = RD.read_dir_tiff_files('data/20210818 SERS timed immersion experiment/5')

### Unknown data???

In [11]:
f_sup_unknown, analyte_unknown = RD.read_dat_file('data/anvar 10-29/area1_Exported.dat')

### Older MG data (Substrate)

In [12]:
f_sup_set_1, MG_set1 = RD.read_dir_tiff_files('data/MG set 1')

f_sup_set_3, MG_set3 = RD.read_dir_dat_files('data/MG-3_15000_ppb')

f_sup_set_4, MG_set4 = RD.read_dir_dat_files('data/MG-4_1500_ppb')

f_sup_set_5, MG_set5 = RD.read_dir_dat_files('data/MG-5_150_ppb')

### Mixes of analytes

In [13]:
f_sup_mix_analytes, Acephate_10_2M = RD.read_dir_tiff_files('data/SERS with mix analyte/Acephate 10-2M 5715minutes')
_, MG_10_5M = RD.read_dir_tiff_files('data/SERS with mix analyte/MG 10-5M 930minutes')
_, mix_1115_min_1 = RD.read_tiff_file('data/SERS with mix analyte/mix/1115min/Mix-SERS-A-(1)-1115min_532nm_Newton_105um _ND1-51_20x-NA0.75_1500ms 1avg 2box (S-S-H-C).tif')
_, mix_1115_min_2 = RD.read_tiff_file('data/SERS with mix analyte/mix/1115min/Mix-SERS-A-(2)-1115min_532nm_Newton_105um _ND1-51_20x-NA0.75_1500ms 1avg 2box (S-S-H-C).tif')
mix_1115_min = np.concatenate((mix_1115_min_1, mix_1115_min_2), axis=0)

_, mix_4027_min_1 = RD.read_tiff_file('data/SERS with mix analyte/mix/4027min/Mix-SERS-A-(1)-4027min_532nm_Newton_105um _ND1-51_20x-NA0.75_1500ms 1avg 2box (S-S-H-C).tif')
_, mix_4027_min_2 = RD.read_tiff_file('data/SERS with mix analyte/mix/4027min/Mix-SERS-A-(2)-4027min_532nm_Newton_105um _ND1-51_20x-NA0.75_1500ms 1avg 2box (S-S-H-C).tif')
mix_4027_min = np.concatenate((mix_4027_min_1, mix_4027_min_2), axis=0)

### Some Acephate data

In [14]:
f_sup_acephate, Acephate_exported = RD.read_dat_file('data/Acephate_Exported.dat')

### Combine all MG data

In [15]:
MG = {**MG_10_5M, **MG_colloidal_SERS_test_20210319, **MG_colloidal_SERS_test_20210331, **MG_ACE_ACETAMIPRID_colloidal_SERS3_20210427,
      **MG_set5, **MG_set1, **MG_set3, **MG_set4, **MG_1_5ppb_0427, **MG_15ppb_0427, **MG_150ppb_0427, **MG_150ppb_0707,
      **MG_150ppb_0707, **MG_150ppb_0811, **MG_150ppb_0707_power_test, **MG_150ppb_0707_power_test, **HWP36_to_80_step2_10s_20210331,
      **batch2_power_test_20210331}

### Combine all Carbendazim data

In [16]:
Carbendazim = {**Carbendazim_0707, **Carbendazim_0707_power_test, **Carbendazim_0722, **Carbendazim_0722_power_test,
               **Carbendazim_0810, **Carbendazim_0811, **Carbendazim_0813, **Carbendazim_0818, **Carbendazim_old_colloids_0813,
               **Carbendazim_old_colloids_0818, **Old_Carbendazim_old_colloids_0813}

### Combine all Thiacloprid data

In [17]:
Thiacloprid = {**Thiacloprid_0707, **Thiacloprid_0707_power_test, **Thiacloprid_0722, **Thiacloprid_0722_power_test}

### Combine all Imidacloprid data

In [18]:
Imidacloprid = {**Imidacloprid_0707, **Imidacloprid_0707_power_test, **Imidacloprid_0722, **Imidacloprid_0722_power_test}

### Combine all Acetamiprid data

In [19]:
Acetamiprid = {**Acetamiprid_0707, **Acetamiprid_0707_power_test, **Acetamiprid_0722, **Acetamiprid_0722_power_test,
               **Acetamiprid_0810, **Acetamiprid_0811, **Acetamiprid_0813, **Acetamiprid_0818, **Acetamiprid_0427,
               **Acetamiprid_old_colloids_0813, **Acetamiprid_old_colloids_0818, **Acetamiprid_old_colloids_v2_0818,
               **Acetamiprid_old_colloids_v3_0818, **Old_Acetamiprid_old_colloids_0813}

### Combine all Acephate data

In [20]:
Acephate = {**Acephate_0707, **Acephate_0707_power_test, **Acephate_0722, **Acephate_0722_power_test, **Acephate_0810,
            **Acephate_0811, **Acephate_0813, **Acephate_0818, **Acephate_10_2M, **ACE_0427}

#### Need to add Acephate_Exported

### Combine all mixes data

In [21]:
Mixes = {**Carbendazim_Acephate_0810, **Carbendazim_Acephate_0811, **Carbendazim_Acephate_0813,
         **Carbendazim_Acephate_0818, **Acetamiprid_Acephate_0810, **Acetamiprid_Acephate_0813, **Acetamiprid_Acephate_0811,
         **Acetamiprid_Acephate_0818, **Carbendazim_Acetamiprid_Acephate_0810, **Carbendazim_Acetamiprid_Acephate_0811,
         **Carbendazim_Acetamiprid_Acephate_0813, **Carbendazim_Acetamiprid_Acephate_0818, **MG_ACE_ACETAMIPRID_colloidal_SERS3_20210427,
         }

#### Add min_1115_min and mix_4027_min

### Convert data to numpy array

#### MG data

In [33]:
all_arr = []
for item in list(MG.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

In [34]:
MG_dataset = np.array(all_arr1, dtype=np.float64)

Make dataset contiguous

In [66]:
np.ascontiguousarray(MG_dataset)

array([[-8.00018311e-01,  1.40002441e+00,  1.40002441e+00, ...,
         2.41199982e+02,  2.40199982e+02,  2.41999969e+02],
       [-3.80001831e+00, -3.39999390e+00, -3.99993896e-01, ...,
         2.24999969e+02,  2.26800018e+02,  2.35600006e+02],
       [-1.16000061e+01, -2.39999390e+00, -5.99975586e-01, ...,
         2.08800018e+02,  1.98199982e+02,  2.22800018e+02],
       ...,
       [ 3.55000000e+02,  3.58000000e+02,  3.99000000e+02, ...,
         3.81000000e+02,  4.00000000e+02,  4.16000000e+02],
       [ 3.33000000e+02,  3.43000000e+02,  3.57000000e+02, ...,
         3.66000000e+02,  3.78000000e+02,  3.51000000e+02],
       [ 3.27000000e+02,  3.66000000e+02,  3.88000000e+02, ...,
         3.59000000e+02,  3.48000000e+02,  3.49000000e+02]])

Check if it worked

In [67]:
MG_dataset.flags['C_CONTIGUOUS']

True

Save dataset

In [69]:
filename = 'MG_dataset.npy'
np.save(filename, MG_dataset, allow_pickle=False)

#### Carbendazim data

In [35]:
all_arr = []
for item in list(Carbendazim.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

In [36]:
Carbendazim_dataset = np.array(all_arr, dtype=np.float64)

Make dataset contiguous

In [76]:
np.ascontiguousarray(Carbendazim_dataset)

array([[330., 351., 387., ..., 464., 472., 490.],
       [ -4., -11.,   2., ...,   7.,   5.,   2.],
       [-12.,  -6.,   3., ..., 165., 134., 147.],
       ...,
       [ -1.,  10.,  -3., ...,  14.,   9.,  14.],
       [  1.,   1., -10., ...,  11.,   7.,  19.],
       [ -1.,   0., -10., ...,  15.,  14.,   3.]])

Save dataset

In [83]:
filename = 'Carbendazim_dataset.npy'
np.save(filename, Carbendazim_dataset, allow_pickle=False)

#### Thiacloprid data

In [37]:
all_arr = []
for item in list(Thiacloprid.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

In [38]:
Thiacloprid_dataset = np.array(all_arr, dtype=np.float64)

Make dataset contiguous

In [78]:
np.ascontiguousarray(Thiacloprid_dataset)

array([[370., 364., 326., ..., 649., 709., 618.],
       [348., 383., 323., ..., 542., 551., 524.],
       [  2.,   3.,   4., ...,  52.,  50.,  23.],
       ...,
       [ 27.,  20.,  29., ...,  37.,  32.,  56.],
       [ 34.,  33.,  47., ...,  76.,  81.,  95.],
       [ 26.,  33.,  44., ...,  71.,  55.,  74.]])

Save dataset

In [84]:
filename = 'Thiacloprid_dataset.npy'
np.save(filename, Thiacloprid_dataset, allow_pickle=False)

#### Imidacloprid data

In [39]:
all_arr = []
for item in list(Imidacloprid.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

In [40]:
Imidacloprid_dataset = np.array(all_arr, dtype=np.float64)

Make dataset contiguous

In [80]:
np.ascontiguousarray(Imidacloprid_dataset)

array([[351., 335., 332., ..., 462., 494., 534.],
       [  4.,   0.,   9., ...,  23.,  19.,  11.],
       [  1.,  13.,  19., ...,  34.,  17.,  25.],
       ...,
       [  9.,  17.,  32., ...,  41.,  63.,  47.],
       [ 20.,  26.,  38., ...,  61.,  66.,  57.],
       [ 19.,   5.,  27., ...,  76.,  33.,  45.]])

Save dataset

In [85]:
filename = 'Imidacloprid_dataset.npy'
np.save(filename, Imidacloprid_dataset, allow_pickle=False)

#### Acetamiprid data

In [41]:
all_arr = []
for item in list(Acetamiprid.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

In [42]:
Acetamiprid_dataset = np.array(all_arr, dtype=np.float64)

Make dataset contiguous

In [81]:
np.ascontiguousarray(Acetamiprid_dataset)

array([[ -4.,  -2.,  13., ..., 240., 210., 189.],
       [ -6.,   7.,  15., ..., 220., 205., 252.],
       [ -6.,   4.,   2., ..., 259., 210., 241.],
       ...,
       [ -1.,   6., -16., ...,  54.,  69.,  54.],
       [-10.,  14.,   2., ...,  55.,  54.,  72.],
       [  5.,   5.,  15., ...,  59.,  79.,  63.]])

Save dataset

In [86]:
filename = 'Acetamiprid_dataset.npy'
np.save(filename, Acetamiprid_dataset, allow_pickle=False)

#### Acephate data

In [47]:
all_arr = []
for item in list(Acephate.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

Add unmerged Acephate_exported data

In [48]:
all_arr.append(Acephate_exported)

In [49]:
Acephate_numpy = np.array(all_arr, dtype=np.float64)

In [50]:
Acephate_dataset = np.copy(Acephate_numpy)

Make dataset contiguous

In [82]:
np.ascontiguousarray(Acephate_dataset)

array([[ 3.42000e+02,  3.38000e+02,  3.58000e+02, ...,  5.08000e+02,
         5.06000e+02,  5.16000e+02],
       [-3.00000e+00, -9.00000e+00,  0.00000e+00, ...,  1.90000e+01,
         6.00000e+00,  3.00000e+00],
       [ 1.30000e+01,  3.00000e+00, -6.00000e+00, ...,  1.20000e+01,
        -2.00000e+00,  1.60000e+01],
       ...,
       [ 1.98200e+03,  2.88000e+03,  4.42000e+03, ...,  1.45540e+04,
         1.45930e+04,  1.46350e+04],
       [ 1.93200e+03,  2.91200e+03,  4.23300e+03, ...,  1.39490e+04,
         1.39200e+04,  1.38530e+04],
       [-1.70367e+00, -2.53702e+00, -3.66666e+00, ...,  8.07410e+00,
        -1.46295e+00,  5.48151e+00]])

Save dataset

In [87]:
filename = 'Acephate_dataset.npy'
np.save(filename, Acephate_dataset, allow_pickle=False)

#### Mix of data

In [60]:
all_arr = []
for item in list(Mixes.values()):
    if item.ndim > 1:
        for nested_item in item:
            all_arr.append(nested_item)
    elif item.ndim == 1:
        all_arr.append(item)

Add unmerged mixes

In [61]:
Mixes_numpy_1 = np.array(all_arr, dtype=np.float64)

In [62]:
Mixes_numpy_2 = np.concatenate((Mixes_numpy_1, mix_1115_min), axis=0)

In [63]:
Mixes_numpy_3 = np.concatenate((Mixes_numpy_2, mix_4027_min), axis=0)

In [64]:
Mixes_numpy = np.array(all_arr, dtype=np.float64)

In [65]:
Mixes_dataset = np.copy(Mixes_numpy_3)

Make dataset contiguous

In [ ]:
np.ascontiguousarray(Mixes_dataset)

Save dataset

In [88]:
filename = 'Mixes_dataset.npy'
np.save(filename, Mixes_dataset, allow_pickle=False)